### ISSUE TITLE
bert_model not used

### ISSUE THREAD

**Issue by senisioi** [IntelLabs/academic-budget-bert#15]
Hi I noticed some inconsistencies in the `create_pretraining_data` script and wanted to make sure they don't generate any further issues,

1. The script `data/create_pretraining_data.py` has an unused argument `bert_model`. Should it be used for anything?
2. And BertTokenizer [is instantiated with max_len 512](https://github.com/IntelLabs/academic-budget-bert/blob/ea000838156e3be251699ad6a3c8b1339c76e987/dataset/data/create_pretraining_data.py#L610). Shouldn't it rather be with `max_seq_length`?

Best!

**Comment by peteriz** [comment]
Hi @senisioi 

1. It does not affect the output of the script. I presume that the original authors were planning to utilize the model name for loading the appropriate tokenizer (with autotokenizer). 
2. I reviewed the documentation of BertTokenizer and `max_len` has no side effects on the tokenizer. Also, the tokenizer must no truncate any sequences since it is done in the samples generation method. In general, it is mainly used to convert str->token ids.

**Comment by senisioi** [comment]
perfect, thanks!
